# Generated by Django 4.2.13 on 2024-05-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_ids',
            field=models.TextField(verbose_name='Product IDs'),
        ),
    ]
